version: v0
scripts:
  - name: 'name'
    script: 'script'
    timeout: 'timeout'
    pattern: 'regex'
    credentials:
    - host: 'localhost'
      port: 22
      user: 'exampleuser'
      keyfile: '/home/bri4/.ssh/id_rsa'
